version: '3.8'

services:
  worker:
    build: .
    command:  celery -A background.celery_app.app worker --loglevel=INFO -Q csmoney_queue -P solo -n csmoney
    restart: always
    env_file:
      - .env
  beat:
    build: .
    command: celery -A background.celery_app.app beat
    restart: always
    env_file:
      - .env
  server:
    build: .
    restart: always
    command: bash -c "
      flask db upgrade &&
      gunicorn main:app -b 0.0.0.0:80"
    env_file:
      - .env
    ports:
      - "80:80"

